require_relative '../lib/book'
require_relative '../lib/rental'
require_relative '../lib/person'
require_relative '../lib/student'
require_relative '../lib/teacher'
require_relative '../helpers/get_name_and_age'
